# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies for build
      run: dotnet restore ./src/PQCons.Tasks/PQCons.Tasks.csproj
    - name: Build
      run: dotnet build ./src/PQCons.Tasks/PQCons.Tasks.csproj --no-restore
    - name: Restore dependencies for test
      run: dotnet restore ./test/PQCons.Tasks.Test/PQCons.Tasks.Test.csproj
    - name: Test
      run: dotnet test ./test/PQCons.Tasks.Test/PQCons.Tasks.Test.csproj --no-build --verbosity detailed